angular.module('firstMakersApp').run(['gettextCatalog', function (gettextCatalog) {
    /* jshint -W100 */
    gettextCatalog.setStrings('en',{
        "Las placas están en siendo probadas en nuestros laboratorios (fase de prototipo) y pronto estarán disponibles para el público.":"The Shield are being tested in our laboratories (prototype stage) and will soon be available to the public.",
        "Descargas":"Downloads",
        "Descargar":"Download",
        "Portada":"Home",
        "Ejemplos":"Examples",
        "Es muy fácil dar los primeros pasos para programar los objetos que te rodean (¡y conectarlos a la Internet!)":"Very easy to give your first steps programming objects around you (and connect them to the Internet)!","Este software se ha construido sobre":"This software has been built on top of",
        "Iniciándose":"Getting Started",
        "La version 0.0.6 funcionará con nuestro prototipo de segunda generación \"First Makers v1.0\" (pronto a ser liberado).":"Version 0.0.6 will work with our second generation prototype board \"First Makers v1.0\" (soon to be released).",
        "La versión 0.3 funciona con nuestro prototipo de primera generación (Tide Makers).":"Version 0.3 works with our first generation prototype board (Tide Makers).",
        "No hay necesidad de soldar componentes, ni tener conocimiento especializado de electrónica.  Sólo se necesita tu curiosidad y creatividad para empezar a conectar y controlar los objetos que te rodean.":"No need to solder, nor having especialised knowledge of electronics. Just need your curiosity and creativity to start connecting and controlling objects around you.",
        "Código fuente":"Source code",
        "Placa First Makers - una placa para Arduino prearmada con sensores y actuadores.  Es fácilmente ampliable con módulos externos (más sensores y actuadores) que se conectan con conectores comunes de 3.5mm (como los que se usan para conectar auriculares).":"First Makers Board - shield for Aduino prebuilt with sensors and actuators.  It is easily expandable with external modules (more sensors and actuators) that can be connected with common 3.5mm connector (like the ones used for connecting earphones).",
        "Software First Makers - software abierto que permite controlar tu placa First Makers en pocos minutos. Mediante bloques de programación visual puedes capturar valores de sensores y modificar los actuadores.":"First Makers Software - open source software that allows you to control your First Makers board in a few minutes. Visual programmable blocks let you capture sensor values and modifiy actuators.",
        "un gran proyecto de código abierto desarrollado por Citilab en Cataluña.":"a great opensource project developed by Citilab in Catalonia.",
        "¡Simplificando los primeros pasos de jóvenes creadores!":"Making it simple for young makers!"
    });
    gettextCatalog.setStrings('es', {
        "The Shield are being tested in our laboratories (prototype stage) and will soon be available to the public.":"Las placas están en siendo probadas en nuestros laboratorios (fase de prototipo) y pronto estarán disponibles para el público.",
        "Downloads":"Descargas",
        "Home":"Portada",
        "Getting Started":"Iniciándose",
        "Examples":"Ejemplos",
        "Download":"Descargar",
        "First Makers Board - shield for Aduino prebuilt with sensors and actuators.  It is easily expandable with external modules (more sensors and actuators) that can be connected with common 3.5mm connector (like the ones used for connecting earphones).":"Placa First Makers - una placa para Arduino prearmada con sensores y actuadores.  Es fácilmente ampliable con módulos externos (más sensores y actuadores) que se conectan con conectores comunes de 3.5mm (como los que se usan para conectar auriculares).",
        "First Makers Software - open source software that allows you to control your First Makers board in a few minutes. Visual programmable blocks let you capture sensor values and modifiy actuators.":"Software First Makers - software abierto que permite controlar tu placa First Makers en pocos minutos. Mediante bloques de programación visual puedes capturar valores de sensores y modificar los actuadores.",
        "Making it simple for young makers!":"¡Simplificando los primeros pasos de jóvenes creadores!",
        "No need to solder, nor having especialised knowledge of electronics. Just need your curiosity and creativity to start connecting and controlling objects around you.":"No hay necesidad de soldar componentes, ni tener conocimiento especializado de electrónica.  Sólo se necesita tu curiosidad y creatividad para empezar a conectar y controlar los objetos que te rodean.",
        "Source code":"Código fuente",
        "The boards are currently being tested (prototype stage) and soon will be available to the public.":"Las placas están en siendo probadas en nuestros laboratorios (fase de prototipo) y pronto estarán disponibles para el público.",
        "This software has been built on top of":"Este software se ha construido sobre","Very easy to give your first steps programming objects around you (and connect them to the Internet)!":"Es muy fácil dar los primeros pasos para programar los objetos que te rodean (¡y conectarlos a la Internet!)",
        "a great opensource project developed by Citilab in Catalonia.":"un gran proyecto de código abierto desarrollado por Citilab en Cataluña.",
        "FirstMakers - shield for Aduino prebuilt with sensors, actuators and easily exnadable with modules that can be connected with a simple 3.5mm (earphone) connector.":"First Makers - placa para Arduino preparada con sensores, actuadores y fácilmente expandible con módulos que se conectan con un simple conector de 3.5mm (el que se usa en los audífonos de música)."
    });
    //gettextCatalog.setStrings('es', {"Download":"Descargar","First Makers Board - shield for Aduino prebuilt with sensors and actuators.  It is easily expandable with external modules (more sensors and actuators) that can be connected with common 3.5mm connector (like the ones used for connecting earphones).":"Placa First Makers - una placa para Arduino prearmada con sensores y actuadores.  Es fácilmente ampliable con módulos externos (más sensores y actuadores) que se conectan con conectores comunes de 3.5mm (como los que se usan para conectar auriculares).","First Makers Software - open source software that allows you to control your First Makers board in a few minutes. Visual programmable blocks let you capture sensor values and modifiy actuators.":"Software First Makers - software abierto que permite controlar tu placa First Makers en pocos minutos. Mediante bloques de programación visual puedes capturar valores de sensores y modificar los actuadores.","Making it simple for young makers!":"¡Simplificando los primeros pasos de jóvenes creadores!","No need to solder, nor having especialised knowledge of electronics. Just need your curiosity and creativity to start connecting and controlling objects around you.":"No hay necesidad de soldar componentes, ni tener conocimiento especializado de electrónica.  Sólo se necesita tu curiosidad y creatividad para empezar a conectar y controlar los objetos que te rodean.","Source code":"Código fuente","The boards are currently being tested (prototype stage) and soon will be available to the public.":"Las placas están en siendo probadas en nuestros laboratorios (fase de prototipo) y pronto estarán disponibles para el público.","This software has been built on top of":"Este software se ha construido sobre","Very easy to give your first steps programming objects around you (and connect them to the Internet)!":"Es muy fácil dar los primeros pasos para programar los objetos que te rodean (¡y conectarlos a la Internet!)","a great opensource project developed by Citilab in Catalonia.":"un gran proyecto de código abierto desarrollado por Citilab en Cataluña.","FirstMakers - shield for Aduino prebuilt with sensors, actuators and easily exnadable with modules that can be connected with a simple 3.5mm (earphone) connector.":"First Makers - placa para Arduino preparada con sensores, actuadores y fácilmente expandible con módulos que se conectan con un simple conector de 3.5mm (el que se usa en los audífonos de música)."});
    /* jshint +W100 */
}]);